[package]
name = "game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bronze = { path = "../bronze" }
bronze_macros = { path = "../bronze_macros" }
strum = "0.24.1"
strum_macros = "0.24.3"
